version: "3.4"

services:
  main-docs:
      image: main-docs:local
      container_name: main-docs
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - NG_SERVER_NAME=localhost
        - NG_LISTEN=3000
      ports: [3000:3000]