version: "3.4"

services:
  blinkid-docs:
      image: blinkid-docs:local
      container_name: blinkid-docs
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - NG_SERVER_NAME=localhost
        - NG_LISTEN=3000
      ports: [3000:3000]