import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { id } from './build/assets/js/reactPlayerDailyMotion.76ff87bf';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type:"html",
      value:'<span style="color:#2F4361">PRODUCT GUIDE </span>'
    },
    {
      type:'category',
      label: "BlinkId Introduction",
      link: {
        type: 'generated-index',
        title: 'BlinkId Introduction',
        slug: '/category/blinkid-introduction/',
        keywords: ['guides'],
        image: '@site/static/logo-microblink.svg',
      },

      items:[
        'blinkid-introduction/overview',
        'blinkid-introduction/privacy',
        'blinkid-introduction/use-cases',
        'blinkid-introduction/non-developer-video-guid',

      
      ]
    },
    {
      type:'category',
      label: "BlinkId Specifications",

      link: {
        type: 'generated-index',
        title: 'BlinkId Specifications',
        slug: '/category/blinkid-specifications/',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },

      items:[
        'blinkid-specifications/platforms',
        'blinkid-specifications/licensing',
        'blinkid-specifications/user-experience',
        'blinkid-specifications/best-practices',

      
      ]
    },
    {
      type: "html",
      value: '<div style="margin-top: 57px;"></div>'
    },
    
    {
      type:"html",
      value:'<span className="sidebarHeadings">DEVELOPERS GUIDE </span>'
    },
    {
      type:'doc',
      id:'video-guides',
      label:'Video guides',
    },
    {
      type: 'category',
      label:'Mobile & Web SDKs',
      items:[
        {
          type:"link",
          label:'iOS',
          href: 'https://github.com/BlinkID/blinkid-ios',
        },
        {
          type:"link",
          label:'Android',
          href: 'https://github.com/BlinkID/blinkid-android',
        },
        {
          type:"link",
          label:'Flutter',
          href: 'https://github.com/BlinkID/blinkid-flutter',
        },
        {
          type:"link",
          label:'React Native',
          href: 'https://github.com/BlinkID/blinkid-react-native',
        },
        {
          type:"link",
          label:'In Browser',
          href: 'https://github.com/BlinkID/blinkid-in-browser',
        },
        {
          type:"link",
          label:'Cordova',
          href: 'https://github.com/BlinkID/blinkid-cordova',
        },
        {
          type:"link",
          label:'Capacitor',
          href: 'https://github.com/BlinkID/blinkid-capacitor',
        },
        {
          type:"link",
          label:'Browser SDK',
          href: 'https://github.com/BlinkID/blinkid-in-browser',
        },
        {
          type:"link",
          label:'Self-hosted',
          href: 'https://docs.microblink.com/documentation/self-hosted/current/overview.html#introduction',
        },
      ]
    },
    {
      type: "html",
      value: '<div style="margin-top:32px;"></div>'
    },
    {
      type:'doc',
      id:'faq',
      label:'FAQ',
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: {type: 'doc', id: 'release-notes/index'},

      items: [
        'release-notes/android',
        'release-notes/ios',
        'release-notes/cordova',
        'release-notes/capacitor',
        'release-notes/flutter',
        'release-notes/react-native',
        'release-notes/in-browser',
      ],
    },
    
    {
      type:"link",
      label:'Product updates',
      href: 'https://microblink.com/resources/product-updates/',
    },
    
   // { type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
]};

export default sidebars;
